---
title: "Problem 2 Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(viridis)
library(p8105.datasets)
library(plotly)

data(rest_inspec)

set.seed(1)
inspectbl <- rest_inspec %>% 
  select(boro,critical_flag,cuisine_description,dba,inspection_date,
         score) %>% 
  filter(!is.na(dba),!is.na(score),boro=="MANHATTAN",
         cuisine_description %in% c("Chinese","Korean","Japanese","Asian"),
         str_detect(inspection_date,c("2017","2016","2015","2014"))) %>%
  sample_n(3000)

inspec_date <- as.character(pull(inspectbl,inspection_date))
for (i in 1:length(inspec_date)) {
  if (str_detect(inspec_date[i],"2014")) {
    inspec_date[i] <- "2014"
  } else if (str_detect(inspec_date[i],"2015")) {
    inspec_date[i] <- "2015"
  } else if (str_detect(inspec_date[i],"2016")) {
    inspec_date[i] <- "2016"
  } else {
    inspec_date[i] <- "2017"
  }
} 
inspec_date <- factor(inspec_date) %>% relevel(ref = "2014")
inspectbl[,5] <- inspec_date

cuisinefct <- factor(pull(inspectbl,cuisine_description)) %>% 
  forcats::fct_relevel(c("Asian","Chinese","Japanese","Korean"))
inspectbl[,3] <- cuisinefct

```

Column {data-width=650}
-----------------------------------------------------------------------

### Chart A

```{r}
criticplt <- inspectbl %>% group_by(inspection_date,
                       cuisine_description,critical_flag) %>% 
  summarize(n=n()) %>% 
  filter(critical_flag %in% c("Critical","Not Critical"),
         inspection_date=="2017") %>% 
  ggplot(aes(x=cuisine_description,y=n,fill=critical_flag))+
  geom_bar(stat="identity")+
  scale_fill_viridis(name="Violation",discrete=TRUE)+
  labs(
    x="Cuisine",
    y="Counts",
    title="2017 Violation plot"
  )+
  theme(plot.title = element_text(face="bold"))+
  theme_classic()

ggplotly(criticplt)
```

Column {data-width=350}
-----------------------------------------------------------------------

### Chart B

```{r}
scoreplt <- inspectbl %>% 
  filter(inspection_date=="2017") %>% 
  ggplot(aes(x=cuisine_description,y=score,fill=cuisine_description))+
  geom_boxplot(alpha=0.7)+
  scale_fill_viridis(name="Cuisine",discrete = TRUE)+
  labs(
    x="Cuisine",
    y="Score",
    title="2017 Asian Cuisine Score plot"
  )+
  theme(plot.title = element_text(face = "bold"))+
  theme_classic()
  
ggplotly(scoreplt)
```

### Chart C

```{r}
yearplt <- inspectbl %>% 
  group_by(inspection_date,cuisine_description) %>%
  summarize(average=mean(score)) %>% 
  ggplot(aes(x=inspection_date,y=average,
             color=cuisine_description,group=cuisine_description))+
  geom_point()+
  geom_line(alpha=0.5)+
  geom_smooth(method = lm, se=FALSE)+
  scale_color_viridis(name="Cuisine",discrete = TRUE)+
  labs(
    x="Year",
    y="Annual Mean of Score",
    title = "2014-2017 Annual Score Plot"
  )+
    theme(plot.title = element_text(face="bold"))+
    theme_classic()

ggplotly(yearplt)
```

